### ISSUE TITLE
Reorganize launch files

### ISSUE THREAD

**Issue by jzheng84** [RoboJackets/igvc-software#104]
Simplify launch procedure so that everyone can easily launch the robot

**Comment by JasonGibson274** [comment]
There should be a launch file that will launch everything needed to drive the robot forward (motor controller, light controller, etc) I should be able to publish to /motors and the robot will drive.

**Comment by JasonGibson274** [comment]
add a motor controller node to the joystick launch file so that all that needs to be launched to joystick robot around is one file

**Comment by JasonGibson274** [comment]
ensure that all sensors are launched in sensors.launch

**Comment by JasonGibson274** [comment]
All of the specific things mentioned are solved and any specific changes should be their own issue
