### ISSUE TITLE
Fix CircleCI On IGVC master

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/igvc-software#114]
I'm going to spend a bit of my time trying to fix master's build for circleci. 

I'll check off things as I get to them
- [x] Fix submodule URL - igvc/src/waypoint_source/geographic_info: @rmkeezer 
- [x] Upgrade to Kinetic - @jgkamat 
- [x] Remove flycapture dependency - @jgkamat

**Comment by jgkamat** [comment]
@rmkeezer could you fix the broken submodule link described above? I could help you out but I'm not sure if thats needed or not.

**Comment by rmkeezer** [comment]
fixed by #118
