### ISSUE TITLE
Stop throwing char* or any other primitives/pointers/etc

### ISSUE THREAD

**Issue by red-eight** [RoboJackets/igvc-software#125]
We should throw C++ exception classes instead of primitives or pointers.

The [<stdexcept> header](http://en.cppreference.com/w/cpp/header/stdexcept) has about 10 different types of exception classes; all of them inherit from [std::exception](http://en.cppreference.com/w/cpp/error/exception). 

Because all of these classes inherit from `std::exception`, we only have to write: `catch (const std::exception &e)`, but we can throw any of these types of exceptions. We can also create our own exceptions, but they should also inherit from `std::exception`.

**Comment by rmkeezer** [comment]
Good idea! This will also help with creating working test cases (when someone decides to add some)

**Comment by sunny3728** [comment]
Already been fixed.
