### ISSUE TITLE
Generic Computer Vision Module

### ISSUE THREAD

**Issue by rmkeezer** [RoboJackets/igvc-software#132]
Create a module that contains common methods used by computer vision modules (lines, potholes, flags)

This may include blocking out parts of the robot from the camera image, blocking out the barrels, converting 2d image to 3d overhead view, etc.

**Comment by dpattison3** [comment]
Possible repeat of #76 
Regardless, should also consider: #51, #72, #105, and of course #76

**Comment by rmkeezer** [comment]
#136 and #138 solves this so far
