### ISSUE TITLE
List of quick workarounds that need to be fixed later

### ISSUE THREAD

**Issue by rmkeezer** [RoboJackets/igvc-software#147]
Prime example: #146 
- [ ] #146 
- [x] #187

**Comment by JasonGibson274** [comment]
https://github.com/RoboJackets/igvc-software/blob/master/igvc/src/scan_to_pointcloud/main.cpp#L46

**Comment by JasonGibson274** [comment]
- [ ] add file types to all files, launch files

**Comment by JasonGibson274** [comment]
unnecessary
