### ISSUE TITLE
write a script to dynamically create a texture map for the ground plane

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#178]

**Comment by JasonGibson274** [comment]
Check the AutoRally repository for a script

**Comment by JasonGibson274** [comment]
This includes writing 3 world files. One for the qualification course, one for the basic course, one for the advanced course.

**Comment by JasonGibson274** [comment]
Talk to me before starting

**Comment by JasonGibson274** [comment]
look here https://github.com/AutoRally/autorally/blob/kinetic-devel/autorally_description/scripts/createTextureImage.py

**Comment by atuttle7** [comment]
Andrew Tuttle, Keshav Kolur, Akshay Karthik.

**Comment by atuttle7** [comment]
Got merged.
