### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#216]
This will be complete when the Readme is accurate and more specific documentation has been moved to the wiki and linked in the Readme.

**Comment by JasonGibson274** [comment]
make format is not in the readme. Also look at ways of doing this through catkin automatically when catkin_make is run. Also the node list at the bottom is a couple years old.

**Comment by jgkamat** [comment]
Also, it would be nice to add a picture of the robot and/or a picture of igvc-software running, just to give people something to expect :).

**Comment by JasonGibson274** [comment]
add launch instructions for both the physical robot and in gazebo

**Comment by JasonGibson274** [comment]
Make a separate markdown file for the nodes and their published and subscribed topics.

**Comment by JasonGibson274** [comment]
add command to run tests to this readme

**Comment by atuttle7** [comment]
Readme should include build concerns and instructions

**Comment by Alescontrela** [comment]
Still relevant. Detailed wiki update should take place after new planner/occupancy grid are merged into devel.

**Comment by oswinso** [comment]
Closing in favor of #454.
