### ISSUE TITLE
Dockerize Gazebo

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#217]
This will be complete when

- An IGVC docker container can be pulled down from DockerHub and run locally with all necessary information exposed
- This must be tested on Docker for Windows, Docker for Mac, and on Linux
- Necessary Virtual Box configuration to run IGVC code in the VM and share messages with the container documented in the wiki
-

**Comment by atuttle7** [comment]
Nope. (why)
