### ISSUE TITLE
Investigate into making Gazebo more realistic with sensor error 

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#220]
This is more of a research spike. Looking into making gazebo more realistic.
- make texture more similar to the images Jason took at comp (contact him for these files)
- Add slight elevation changes
- make the course more similar to the actual course at competition 
   - more convoluted
   - different color barrels
   - narrower tracks
   - barrels very close together
   - look into adding ramps??
- add error to the sensors
- explore implementing the electrical code for the PID controllers

**Comment by JasonGibson274** [comment]
I think the first step of this issue should be making our world no longer perfectly flat

**Comment by Alescontrela** [comment]
Still relevant
