### ISSUE TITLE
Get Woodi running with joystick

### ISSUE THREAD

**Issue by rmkeezer** [RoboJackets/igvc-software#223]

**Comment by jzheng84** [comment]
Immediate issues:
1) Encoders not returning values
2) Once encoders work, tune PID and observe motor inputs

**Comment by jzheng84** [comment]
Update:
1. Right motor works and returns reasonable encoder values -> PID works
2. Left motor does not move (was moving at one point)

**Comment by JasonGibson274** [comment]
Completed
