### ISSUE TITLE
Create a node for recording the speed of the robot over time

### ISSUE THREAD

**Issue by dpattison3** [RoboJackets/igvc-software#225]
This will be useful as a step in validating the PID tuning. We want to be able to compare the speed published by /motors and the speed recorded on /encoders. This can be done with just a csv file, then plotted in excel.

**Comment by dpattison3** [comment]
related to #224

**Comment by AaronMcDaniel** [comment]
Yo, lemme do this!

**Comment by AaronMcDaniel** [comment]
Never mind. I can assign myself now.

**Comment by barulicm** [comment]
Is this intended to have any functionality beyond what can be accomplished with `rosbag record` and `rqt_plot` (or `rqt_bag`'s plot feature)?

**Comment by JasonGibson274** [comment]
I think a more quantitative measurement of PID tuning would be interesting. I also think that it is a good node to start working with in order to understand how PID works.

**Comment by JasonGibson274** [comment]
Also rqt_plot does not work super well without timestamps which I think this issue will also include resolving parts of #286

**Comment by atuttle7** [comment]
Done. :)
