### ISSUE TITLE
Setup alias commands on Jessii NUCs to streamline operation

### ISSUE THREAD

**Issue by jzheng84** [RoboJackets/igvc-software#226]
Example Freshman project:
"Test motors" alias that runs motors at a desired speed
"Test lidar" to start displaying what the lidar is perceiving

**Comment by JasonGibson274** [comment]
to add along with this might be a quick reference of key commands since there is usually no mouse.

**Comment by Alescontrela** [comment]
This can be accomplished using a combination of `rostopic echo` and rviz. Closing and putting on backlog, as it is not a bug.
