### ISSUE TITLE
use status messages to warn dependent nodes of failure

### ISSUE THREAD

**Issue by dpattison3** [RoboJackets/igvc-software#233]
Increase code safety by publishing status messages from nodes and subscribing to these topics in dependent nodes. Any error should be treated properly so no node is operating with bad data.

**Comment by Alescontrela** [comment]
Effectively, each node should publish what it's meant to publish and a status message on a separate topic?

**Comment by JasonGibson274** [comment]
That was the idea.

**Comment by Alescontrela** [comment]
Still relevant?

**Comment by JasonGibson274** [comment]
you can backlog it, but yes

**Comment by Alescontrela** [comment]
backlogged
