### ISSUE TITLE
set up launch files for multicomputer launch

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#239]
igvc.launch should launch everything on a single computer or on 2 computers if the host exists. This can be done in the launch file be using the machine tag. http://wiki.ros.org/roslaunch/XML/machine

**Comment by AaronMcDaniel** [comment]
I'll try this one.

**Comment by KishoreMayank** [comment]
I will also try this one

**Comment by Alescontrela** [comment]
Is this still necessary?

**Comment by KishoreMayank** [comment]
I am no longer associated with robojackets.

**Comment by JasonGibson274** [comment]
After the new computer no. Until then not really
