### ISSUE TITLE
Convert path planning and mapper to nodelet

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#246]
The giant Octree that is shared between the mapper and the pather should be used as a shared resource between the two nodes.

**Comment by atuttle7** [comment]
No longer an octree, but still applicable

**Comment by Alescontrela** [comment]
Still relevant?

**Comment by oswinso** [comment]
I don't think so?

**Comment by Alescontrela** [comment]
Marking as closed. If this becomes a problem in the future, a more detailed issue can be opened.
