### ISSUE TITLE
Convert image processing nodes to nodelets

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#247]
copying of the image so many times is inefficient. We need to convert out image processing nodes to nodelets so that is can be done faster.

**Comment by atuttle7** [comment]
1.) Convert python TF node to C++
2.) Convert to nodlet

**Comment by Alescontrela** [comment]
Perhaps a better alternative is to convert image processing nodes into [ROS Services](http://wiki.ros.org/Services), which are for all intents and purposes non-blocking processes.

**Comment by JasonGibson274** [comment]
That is not why this exists at all. It is to save time by passing image as a pointer rather than through network stack. camera driver is not very intensive. Cannot do until we move to cpp on vision stuff though

**Comment by Alescontrela** [comment]
Ok, i'll backlog this
