### ISSUE TITLE
Update system stats

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#251]
There is a system stats node that exists in the repository igvc/src/system_stats and a custom message at igvc_msgs/msg/system_stats.msg. We would like this node to publish more information than just cpu and memory usage.

* [ ] CPU temperature
* [ ] Fan speed

**Comment by WinfinitytheStar** [comment]
I'm working on this issue.

**Comment by JasonGibson274** [comment]
@WinfinitytheStar accept the org invite and I can assign you to this issue

**Comment by Alescontrela** [comment]
still relevant?

**Comment by JasonGibson274** [comment]
I think not closed by recent pr
