### ISSUE TITLE
Rviz plugin for sensor status

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#255]
Panel that shows each sensor and if it is publishing data to its topics.

**Comment by KishoreMayank** [comment]
Aaron McDaniel
Soohyun Kim
Mayank Kishore

**Comment by soohyun-kim** [comment]
Gazebo and RVIZ response to Sensor Panels seems to be working; only need the timer component and I think we'll be finished

**Comment by JasonGibson274** [comment]
Resolved
