### ISSUE TITLE
Rviz plugin for the path

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#256]
I would like to see real time stats on the paths we are generating. How curvy they are etc

**Comment by JasonGibson274** [comment]
Talk to me before starting

**Comment by atuttle7** [comment]
Sounds fun.

**Comment by JasonGibson274** [comment]
* [ ] The length of the path
* [ ] number of nodes expanded, edit the path planner to publish this information expanded callback
* [ ] determine measurement of curvyness

**Comment by Alescontrela** [comment]
Field D* super curvy. This is implemented.

**Comment by JasonGibson274** [comment]
This is not implemented... Unless you made a rviz plugin that displays these states which I have not seen yet. Should this be an issue. No but it should go in the backlog
