### ISSUE TITLE
Convert Labelme data to segmentation-like images

### ISSUE THREAD

**Issue by rmkeezer** [RoboJackets/igvc-software#263]
Currently, when you download data from Labelme, we only get the original image and an xml file with coordinates of the polygons and their labels. We want to have an output like the image below instead:

![image](https://user-images.githubusercontent.com/8153045/33244597-9d8432f4-d2c8-11e7-92bf-8b223b17c8cf.png)

Labelme might already have this feature so check their website.

DM dpattison3 or rmkeezer on slack for labelme credentials

Update:
Labelme has a matlab toolkit that appears to be able to transform the .xml polygons into segmentation images. https://github.com/CSAILVision/LabelMeToolbox

**Comment by dpattison3** [comment]
The LabelMe Matlab toolkit makes this very easy. Here's what I used: https://gist.github.com/dpattison3/4c043bff1e2d145ecfb2eacbb67031f4.
