### ISSUE TITLE
Train a CNN for semantic segmentation of objects

### ISSUE THREAD

**Issue by rmkeezer** [RoboJackets/igvc-software#264]
I am currently trying to modify KittiSeg which is a fully convolutional neural network (FCN or CNN) written in tensorflow that outputs tensorflow models.

https://github.com/MarvinTeichmann/KittiSeg
https://www.tensorflow.org/install/

I recommend using these from my exploration on CNN tools. Other options include using Caffe2, Theano, or PyTorch and some other semantic segmentation repo on github.

**Comment by dpattison3** [comment]
KittiSeg seems to work well. We now need to make it run in a ros node on the robot

**Comment by rmkeezer** [comment]
Update: the tensorflow kittiseg model does run in a rosnode using python. The performance might be better if we are able to load the model in C++

**Comment by dpattison3** [comment]
Addressed by pull request #295
