### ISSUE TITLE
Make test case to compare vision changes

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#270]
We would like a ros test case that uses a labeled images to determine the accuracy of the line detector.

* [ ] Use MaxF1
* [ ] average precision
* [ ] accuracy
* [ ] Ensure correct transform

**Comment by Alescontrela** [comment]
Still relevant? How were we measuring accuracy before?

**Comment by JasonGibson274** [comment]
Do you have lableled images??

Yes this is still relevant.

**Comment by Alescontrela** [comment]
Adding this as a subtask to [Re train NN](https://app.clickup.com/t/eymwz)
