### ISSUE TITLE
handle imu bias

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#288]
Our imu has intrinsic bias due to it not being correctly mounted and it results in smearing of the global map since the robot thinks is has a constant acceleration on the y. We need a way to handle this bias in software so that we are not dependent on the imu being mounted perfectly flat. A logical place to start would be reading in the values over a long time and then canceling out the average vector.

**Comment by barulicm** [comment]
I think you've substituted 'lidar' for 'imu' in a few places in this issue.

**Comment by JasonGibson274** [comment]
Fixed that issue

**Comment by Alescontrela** [comment]
Still relevant? I have not witnessed this behavior with the new imus. The only remaining Imu bias is that of electromagnetic interference with the magnetometer.

**Comment by JasonGibson274** [comment]
That’s what this is about
