### ISSUE TITLE
add elevation to gazebo

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#298]
see the instructions here work before going to the gazebo OEM files.

https://github.com/AS4SR/general_info/wiki/Creating-Heightmaps-for-Gazebo

**Comment by AaronMcDaniel** [comment]
@JasonGibson274 Can you link me that .materials file?

**Comment by AaronMcDaniel** [comment]
Found it in #299

**Comment by Alescontrela** [comment]
Currently being implemented, therefore not a bug
