### ISSUE TITLE
Update Gazebo textures

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#299]
Our world looks terrible. Convert the ground plane to a blended texture following this and creating a new material

http://wiki.ogre3d.org/Materials

use white and a grass image to create the ground plane.

**Comment by JasonGibson274** [comment]
https://github.com/AutoRally/autorally/blob/kinetic-devel/autorally_description/urdf/gazebo.material see this for an example of blended textures in gazebo

**Comment by Alescontrela** [comment]
Currently being implemented by @JasonGibson274. Not integrated into current codebase, therefore not a bug
