### ISSUE TITLE
Convert Path Planner to discrete space

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#304]
Our new mapping strategy will use an occupancy grid. The path planner needs to be moved out of continuous space and into discrete space. The map will be created using a matrix (Eigen Matricies most likely) that means that the path will take in the ros equivalent of that type and output a path in (x,y) coordinates relative to the global map (0,0 defined by ekf).

**Comment by Alescontrela** [comment]
Done
