### ISSUE TITLE
Smooth Path in Path Planner

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#305]
after #304 we will need to convert the path into a smooth followable path. The x,y paths will be from center of each grid cell to the next. possible optimization include

- deleting points along a straight line
- bezier curve of path similiar to [RoboCup](https://github.com/RoboJackets/robocup-software/blob/1e7afe85933cac70b8d677c4ea70877a34c1abcf/soccer/planning/RRTPlanner.cpp#L560)

**Comment by Alescontrela** [comment]
Smooth path planner implemented (Field D*)
