### ISSUE TITLE
Convert path following node to trajectory roll out

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#306]
after #305 we will have followable paths. Our current path follower node only sends motor commands to the motors at the right time and has no ability to get back on the path if it diverges. Using the updated position from particle filter based SLAM or EKF if the previous is not implemented yet, we need to roll out N trajectories from the current position and then follow the best one determined by a cost function. Finally the motor controller will then send its command down to the motors to be executed.

**Comment by JasonGibson274** [comment]
Perhaps use this https://en.wikipedia.org/wiki/Midpoint_circle_algorithm

**Comment by Alescontrela** [comment]
Putting in backlog as it is not an issue
