### ISSUE TITLE
Convert Mapper to particle Filter based SLAM

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#307]
This issue is going to cover the entire life cycle of this feature but should be divided into steps. Tasks should be performed in sequential order and this comment should be updated for all relevant information.

### High Level Approach
Our in our particle filter SLAM approach the particles are estimates of the current position. Ignoring initialization entirely the approach is as follows.

1. grab sensor measurements while moving 
2. update particle positions based off the last movement update (from localization)
3. determine which particles are most likely and re-sample with replacement
4. determine the centroid of particles and update map based on sensor readings (this could potentially add obstacles to the map)
5. repeat

Ultimately the map will be an occupancy grid where each square has a probability of being occupied.

###  Unsolved problems
1. distance metric that is robust to new obstacles being added to the map
2. resolving timing differences between sensor measurements 

### Create the map:
Should be backed by some sort of matrix (cv::Mat) that can be serialized into a ROS message either directly or using a package. 

##### Should have parameters:
start x,y of the robot in the grid
length and width of the map (in meters)
resolution of the map

### Get viewable squares
Every particle needs a way to be able to determine what it should be able to see in the current map. Should create a base class with virtual methods with subclasses that implement each sensor (camera and Lidar).

### Actually write particle filter
TBD

### Tuning

**Comment by Alescontrela** [comment]
This was just tried and we decided not go with it. Closing as it is not a big.
