### ISSUE TITLE
Fix URDF for gazebo

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#309]
* [ ] convert two caster balls to a single one or a caster wheel
* [ ] remove axle and direct connect wheels to chassis

**Comment by JasonGibson274** [comment]
The more I think about this issue I am inclined to leave the front caster as a gazebo defined sphere just for ease of use. Also the body CAD needs to be imported in simplified format.

**Comment by Alescontrela** [comment]
Still relevant? I think your gazebo updates address this issue

**Comment by JasonGibson274** [comment]
Nope
