### ISSUE TITLE
Tune covariances matricies

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#314]
Some of our covariance matrices are hard coded and should be checked for validity.

**Comment by dpattison3** [comment]
Could you define what you mean by validity? I am guessing you don't mean the technical validity, as in the matrix must be symmetric and positive semi-definite.

**Comment by JasonGibson274** [comment]
I was just tying to get across the idea that these matrices are approximate.

**Comment by Alescontrela** [comment]
This falls under the general problem of localization, specifically under testing of the current ekf implementation. Task exists
