### ISSUE TITLE
Convert urdf file to use xacro

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#317]
using xarco we will be able to parametrize our urdf file and make the file simpler.

**Comment by JasonGibson274** [comment]
a good example of this is the AutoRally urdf file https://github.com/AutoRally/autorally/blob/kinetic-devel/autorally_description/urdf/autoRallyPlatform.urdf.xacro

**Comment by Alescontrela** [comment]
Currently being implemented by @JasonGibson274 in [this branch](https://github.com/RoboJackets/igvc-software/tree/gazebo_updates). Not integrated into current codebase therefore not a bug
