### ISSUE TITLE
Fix Gazebo run process

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#318]
Our build system segfaults more than it should. I am not sure it is the version of anything we are running or not.

**Comment by JasonGibson274** [comment]
For more information I think this is due to a script spawning the model that used to be required but it should be fixed in latest gazebo udpates

**Comment by barulicm** [comment]
To clarify, you mean Gazebo segfaults, and not your build system, right?

**Comment by barulicm** [comment]
Sweet. Can you point to the source that documents the new version fixing this problem? This has also been plaguing RoboRacing's simulator.

**Comment by JasonGibson274** [comment]
If I find the source I will let you know. I just noticed that the AR and others I work with no longer do this but both RR and IGVC do.

**Comment by JasonGibson274** [comment]
This works now. I changed the code a while ago apparently
