### ISSUE TITLE
Publish ground truth gazebo pose

### ISSUE THREAD

**Issue by dpattison3** [RoboJackets/igvc-software#319]
We should be able to get the ground truth pose (position, orientation, and velocity) when running gazebo. This will be useful for testing and validation any state estimation algorithms.

**Comment by JasonGibson274** [comment]
I looked into this for work. The ROS gazebo plugin does not publish a timestamp for their model states message. So we will have to submit a PR for that change if we want this to be very accurate. Otherwise you will get a pose that is pretty near.

**Comment by JasonGibson274** [comment]
It is a known issue on the Repo https://github.com/ros-simulation/gazebo_ros_pkgs/issues/535

**Comment by Alescontrela** [comment]
still relevant?

**Comment by JasonGibson274** [comment]
Addressed in new PR
