### ISSUE TITLE
Create competition realistic gazebo world

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#324]
Our current gazebo world is too wide with the lines. Create a ground plane that starts out very easy and progressively gets narrower and harder. I also recommend having different launch files and worlds for the the qualification course, the basic course, and then just the most difficult obstacles you can do.

**Comment by Alescontrela** [comment]
This isn’t implemented in the current codebase but is planned. Closing as it is not a bug. Will list as an implementation.
