### ISSUE TITLE
ROS Melodic / Ubuntu 18.04 Readiness

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/igvc-software#326]
Congratulations! I did not find any issues **building** your code with Melodic / 18.04.

However, I did notice that igvc/launch/camera.launch depends on usb_cam. This dependency is not noted in igvc's package.xml, so rosdep won't try to install it. Note that usb_cam is not yet released in Melodic and will have to be built from source.

Please double check your dependency specifications. There may be other run dependencies in the project that have not yet been released in Melodic.

**Comment by barulicm** [comment]
usb_cam is expected to be released as part of the next Melodic sync this Friday. You should not have to build it from source when you switch.

**Comment by Alescontrela** [comment]
Still relevant?

**Comment by barulicm** [comment]
Given you have all been running Melodic/18.04 for the entire school year so far, probably not.
This was from last summer as part of a multi-project audit of Melodic readiness.

**Comment by Alescontrela** [comment]
I figured. Closing this then.
