### ISSUE TITLE
Make Default Configs For RVIZ

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#327]
I would like to be able to launch different rviz configs for different use cases that automatically have all the topics I care about and color coded in a "pretty" way

**Comment by Alescontrela** [comment]
Backlogging this. What I've gathered over the past semester is that rviz configs are developed on an implementation-specific basis. i.e. if i'm testing the path planner, I make an rviz config that helps me visualize the planner. With this in mind, a suitable rviz config structure might be:

```
igvc_rviz_plugins
|__ planner
|   |__ jessii_planner.conf
|__ mapper
|   |__jessii_mapper.conf
|...
```

Then in the launch file for, say, the mapper: 

```xml
<launch>
...
    <group if="$(arg plot_rviz)">
        <node name="jessii_rviz" pkg="rviz" type="rviz" args="-d $(find igvc_rviz_plugins)/configs/mapper/jessii_mapper.rviz"/>
    </group>
</launch>
```
