### ISSUE TITLE
tf Transform on IMU data yielding unexpected results

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/igvc-software#35]
Applying the tf transform /imu -> /base_footprint on the IMU orientation quaternion does not produce the expected output. Grabbing Euler angles from the quaternion before and after the transformation shows the correct transformation in yaw, but leaves roll and pitch untouched.

**Comment by barulicm** [comment]
Hack-ish fix added to Ardupilot node. See igvc/src/ardupilot/ardupilot.cpp:51

**Comment by dpattison3** [comment]
I haven't been able to recreate this issue with the new IMU set up, so I'm going to close the issue.
