### ISSUE TITLE
Missing test cases for scan_to_pointcloud

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#354]
Some how during our move over to the new package structure we deleted the scan_to_pointcloud nodew test cases. RR has some that we can ~**steal**~ use. 

https://github.com/RoboJackets/roboracing-software/blob/master/rr_platform/test/scanToPointCloud/test_scanToPointCloud.cpp

**Comment by Alescontrela** [comment]
Is this still relevant? Could the test cases not be recovered from github history?

**Comment by JasonGibson274** [comment]
It could be. Someone just needs to do it. That’s why it is an issue.

**Comment by oswinso** [comment]
I don't think we have a use for this anymore, as we don't use this node anymore since the switch to the vlp-16
