### ISSUE TITLE
SmoothControl.cpp poor structure

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/igvc-software#356]
SmoothControl.cpp is poorly structured as a class. It uses class members to pass around data to related methods instead of just returning a value. Specifically it uses class members as temporary storage variables.

For example getLineOfSSightAndHeading() returns void and sets the heading_ variable instead of just returning a value from the method. 

class members listed below should be deleted.
* los_
* heading_
* tar_orientation_
* theta_
* delta_
* curPose_

Method should be restructured accordingly.

**Comment by Alescontrela** [comment]
Fixed
