### ISSUE TITLE
Fix build dependency orders related to igvc_msgs

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/igvc-software#40]
On first build, some nodes in IGVC get built before igvc_msgs finishes, causing them to error out. Currently, all builds after the first one work fine, but we should still probably fix this.

**Comment by alchaussee** [comment]
Can run "catkin_make igvc_msgs_gencpp" to build the messages then catkin_make will work

**Comment by jgkamat** [comment]
Running make without `-j2` works, but I can't find how to turn that off in catkin. Also...
![deps](https://cloud.githubusercontent.com/assets/4349709/10064774/386ba46a-624a-11e5-8387-ac743c378de3.png)

**Comment by barulicm** [comment]
That's a work of art

**Comment by jgkamat** [comment]
Whoops
