### ISSUE TITLE
Mapper cannot see objects that are inside the minimum distance

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#406]
If there is a barrel that is occupied, but is inside the minimum lidar range, then the mapper will say that those grid cells are occupied, even though we cannot tell if they are inside the minimum lidar range. The freeSpace should be changed to only say that grid cells from a minimum lidar range onwards are free.

**Comment by Alescontrela** [comment]
Do you mean: 

> If there is a barrel that is occupied, but is inside the minimum lidar range, then the mapper will say that those grid cells are ~occupied~ free
