### ISSUE TITLE
Neural net for barrels

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#427]
Right now, #387 is temporarily hotfixed by #411, but this can be solved better if we have a neural net for barrels, which can then directly remove areas of the camera image which are barrels, and thus we do not have any information on lines about.

We already have labelled images on RJ Cloud, and all we need to do is to train a model. Once the model is trained, we should be able to handle this edge case better.

**Comment by suhacker1** [comment]
Should this be closed now or no?

**Comment by suhacker1** [comment]
Also, not exactly sure how the unassigning happened

**Comment by oswinso** [comment]
Yeah this can be closed with #710
