### ISSUE TITLE
Create ROS parameter checking library

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#467]
RoboRacing currently also has their own ROS parameter checking system in place kinda. See https://github.com/RoboJackets/roboracing-software/blob/fcc0968fc6f41deb73153dee1a39b999f47a281f/rr_common/src/planner/planner_node.cpp#L139-L161

We should extract our current parameter checking / assertion checking system into a library that we can share between the two rj teams.

**Comment by JasonGibson274** [comment]
We should make a RJ common or RJ ROS common repo

**Comment by oswinso** [comment]
cool. I'll ask for a repo made on it-helpdesk

**Comment by oswinso** [comment]
This epic should be completed.
