### ISSUE TITLE
Optimize linedetector.cpp such that it can enforce line lengths in real time

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#50]
Currently linedetector.cpp uses a randomized algorithm to follow a random set of pixels and make sure that they connect through a minimum number of other line pixels in order to enforce that all lines are a certain length. This was done to make processing faster, but we need this algorithm to be deterministic. We cannot occasionally miss lines in images.

**Comment by dpattison3** [comment]
This is no longer the case. Closing because it is outdated.
