### ISSUE TITLE
Stop publishing waypoints after reaching final destination

### ISSUE THREAD

**Issue by tangemicioglu** [RoboJackets/igvc-software#541]
We currently keep publishing waypoints even after reaching the final waypoint, which is pointless and blocks us from sending the robot to alternative destinations via rviz.
We should either kill the waypoint_source or stop publishing after the final waypoint is reached.

AC: `move_base_flex` can navigate to new goals through rviz's 2D Nav Goal after the robot is done with the waypoints.

**Comment by oswinso** [comment]
Fixed since either #623 or #613 or something.
