### ISSUE TITLE
Refactor igvc_perception NN things

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#549]
[cnn.py](https://github.com/RoboJackets/igvc-software/blob/master/igvc_perception/src/cnn/cnn.py) currently is a bit of a mess and needs to be cleaned up. Also, anything related to the NN in the `igvc_perception` folder is messy.

AC: Refactored cnn.py and `igvc_perception`

**Comment by suhacker1** [comment]
#611 falls under this, right?

**Comment by oswinso** [comment]
Yeah... but I guess like it not conforming to pep8 is only a small part of the "mess". The bigger part of this "mess" is that it's got like multiple responsibilities, and the code itself is structured in a mess and not really the styling.
