### ISSUE TITLE
Rviz Plugin - Add a Timer

### ISSUE THREAD

**Issue by alchaussee** [RoboJackets/igvc-software#55]
We need an Rviz plugin which shows a timer that times how long the robot has been running.

Rviz uses the rqt/Qt framework for displaying elements on the screen. It uses message passing with Signals and Slots.

Here is a good tutorial to help get you started with Rviz Plugins.
http://docs.ros.org/jade/api/rviz_plugin_tutorials/html/panel_plugin_tutorial.html

**Comment by barulicm** [comment]
How will this plugin differ from the time display already on the bottom of the Rviz window that shows ROS Elapsed?

**Comment by rmkeezer** [comment]
There is no difference
