### ISSUE TITLE
Change cnn.py to publish new CameraInfo after resizing

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#550]
Currently, [cnn.py](https://github.com/RoboJackets/igvc-software/blob/master/igvc_perception/src/cnn/cnn.py) doesn't publish a new CameraInfo for the resized image after resizing it for feeding it into the neural network.

AC: cnn.py publishing a camerainfo for the resized image.

**Comment by VAM7686** [comment]
I think #833 should close this
