### ISSUE TITLE
Add flake8 to CI

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#551]
We've got clang-format for formatting our C++ side, but we've got nothing for python.

Check [this](https://realpython.com/python-continuous-integration/) out for introduction to flake8.

AC: flake8 added to CI

**Comment by suhacker1** [comment]
I think we can consider this resolved since we added Pep8 Speaks?

**Comment by oswinso** [comment]
Closed as #625 confirms that pep8speaks works.
