### ISSUE TITLE
We don't have a fancy picture on our README

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#586]
Roboracing has a [really nice looking picture of sedanii on their readme](https://github.com/RoboJackets/roboracing-software/tree/feat/271-map-closer), we don't. We're not gonna lose to them.

AC: Nice picture of Jessii on our README.

**Comment by Dallas-D** [comment]
If we are comparing ourselves to RR, we should also add the software lead and project manager icons

**Comment by oswinso** [comment]
Yes, that is correct. Could you do it? @Dallas-D
