### ISSUE TITLE
Compile and Run on TK1 Boards

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#64]
The project must run on the new robot which will be using 3 TK1 boards, instead of the current laptop. This issue is just to get the project building and running on a single tk1 board.

**Comment by barulicm** [comment]
Instructions for installing FTDI Driver kernel module. This is necessary to talk to serial devices (Arduinos, IMU, GPS, etc)
http://elinux.org/Jetson/Tutorials/Program_An_Arduino

**Comment by dpattison3** [comment]
@rmkeezer This no longer applies since we're using the NUCs, right?

**Comment by rmkeezer** [comment]
Correct!
