### ISSUE TITLE
Path Planner Branching Optimization

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#66]
The path planner node currently has variables for determining what angles to search for paths through, and the sizes of the steps to take. It also uses an A\* graph search to determine its path.

Currently the path planner expands many many nodes while searching the graph, many of which are very very close to other expanded nodes. By tuning some of these parameters differently, or making other changes to the path planner, we should be able to reduce the number of nodes which must expand to find a path significantly. This will significantly increase efficiency.

**Comment by dpattison3** [comment]
This might be taken care of with the switch to a different algorithm mentioned in #111. I'll leave it because I am not certain, but the new algorithm will certainly help with the efficiency concern.
