### ISSUE TITLE
IMU heading Sensor Fusion

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#69]
Currently the robot's orientation is determined by the IMU's compass, which is susceptible to noise. The noise can be observed by watching the orientation of the robot as it changes while the robot is stationary.

Implementing a Kalman filter on the IMU compass and dead reckoning from the wheel odometry will improve this reading.

**Comment by dpattison3** [comment]
This should be addressed in the new IMU #106. There are IMUs that have built in Kaman filters with tunable parameters.
Dead reckoning is a bad approach to this. The sensor fusion directly from the IMU is a better idea. This is also more consistent with our goal of better state estimation. Mixing the data sources before integrating them into the state estimator defeats the purpose.
