### ISSUE TITLE
Migrate core to ros2 using ros1_bridge

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-software#695]
For the ros2 migration, we should start by creating a separate branch for this effort, and use [ros1_bridge](https://github.com/ros2/ros1_bridge) to still launch ros1 nodes but in a ros2 environment.

AC: Core is in ros2 and the stack works using`ros1_bridge`

**Comment by matthewhannay567** [comment]
ros2core.sh has been created and placed in the ros2master branch. This script launches both roscore and ros1_bridge, so ros1 and ros2 nodes and communicate.
