### ISSUE TITLE
Test and Tune Pothole Detection

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#70]
The pothole detector is currently tuned for detecting potholes of a certain range of sizes in one particular image. It needs to be tested against many different images and on moving data from multiple data sets, and calibrated/tweeked such that it performs well on all of them.

**Comment by rmkeezer** [comment]
This is a vague issue that has no real goal.
Testing with Gazebo is currently sufficient until the new robot is ready.

**Comment by rmkeezer** [comment]
Although this is vague, pothole detector is detecting circles when just a noise is generated in gazebo grass. It should be more robust than this.

**Comment by dpattison3** [comment]
addressed by #264
