### ISSUE TITLE
Tune PID for new Robot

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#71]
Once the new robot is operational, its PID constants must be tuned. This involves taking the robot out and iterating over many different PID parameters until ones are found which perform well.

PID are Proportional, Integral, and Derivative gains, which are used in a basic control mechanism to account for errors between what we think we are telling the robot to do, and what it actually is doing.

**Comment by thaeds** [comment]
Here's a decent PID tuning guide, you can probably find other better ones too if you want.

**Comment by atuttle7** [comment]
Robot ded
