### ISSUE TITLE
Localizing 2 new cameras

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#73]
Two new downwards facing cameras are to be added to the front of the robot for higher fidelity detection of obstacles in the immediate vicinity.

These two new cameras need calibration, to be included in the tf tree, to have overhead transforms, and to publish the resulting images to sensible topics.

The current architecture for the BumbleBee can be copied somewhat, only simplified, as it is a stereo camera.

**Comment by dpattison3** [comment]
I believe this has been accomplished. Or at least the issue should be narrowed significantly to specify what still needs being done.

**Comment by jzheng84** [comment]
I believe the cameras have been localized, and we were able to map lines detected from those cameras into the point cloud. Couple things that still have to be done:
1) Improve localization (currently the cameras do not look like they are in the correct position on the tf tree)
2) Crop out any unnecessary parts of the image (i.e the vehicle)
3) Find an ideal angle for the cameras to be mounted onto the vehicle so we have a large enough field of view

**Comment by kscharm** [comment]
We have ordered two new side cameras for the new robot. I will be working on the three points mentioned by @jzheng84.

**Comment by rmkeezer** [comment]
The new cameras are already in the TF tree and work in Gazebo. This is completed but more testing should be done when the robot is complete.

**Comment by kscharm** [comment]
We want a tool that can do this for any set up of the cameras. It is possible that the cameras could shift over time. It may be good for setting up new cameras or changing their positions.

**Comment by atuttle7** [comment]
No longer applicable to current platform.
