### ISSUE TITLE
Look at how changing the wheelbase on the new robot effects path planning

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#74]
Currently our path planner assumes a base_frame origin at the center of the robot's rear wheel axle. The new robot however will have a base_frame origin at the center of the center axle, between the two drive wheels.

Changing the location of the base_frame may effect path planning, check to see if it does, and fix any problems encountered.

**Comment by rmkeezer** [comment]
will be looked at in #112
