### ISSUE TITLE
Image Processing Standardization Node

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#76]
We need a new ROS node which takes in camera images and performs standerdizing processes which several other nodes can benefit from on the image. This prevents each of the following nodes from having to duplicate the same work, and reduces the amount of tuning for our vision algorithms.

The first step in this standardization is simply to enforce a uniform average brightness across the image. This should help our other computer vision nodes perform more reliably even when its dark, or bright out.

**Comment by rmkeezer** [comment]
More can be added to the processing but the standardized methods have been made in CVUtils.hpp
