### ISSUE TITLE
Add an additional output topic for pointcloud_filter that removes the ground points.

### ISSUE THREAD

**Issue by matthewhannay567** [RoboJackets/igvc-software#777]
AC: pointcloud_filter publishes to an additional topic which filters out the ground plane points.

**Comment by yyajima21** [comment]
I #806 did we ever check the output of point cloud filter after noetic migration? I don't think the noetic branch has a working point cloud filter. This is the error message I got.

![image](https://user-images.githubusercontent.com/35343680/97820626-f5c84f80-1c7c-11eb-82fb-8ff27f4685fe.png)

**Comment by yyajima21** [comment]
Update: I found out that our point cloud filter folder is outdated. So, I will make another package that removes a ground plane.

**Comment by matthewhannay567** [comment]
What do you mean "outdated"? And when you say "make another package", do you mean another filter .cpp file?
