### ISSUE TITLE
Line Detector: Replace edge kernals with gabor filters

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#78]
Instead of using our current image kernals, use gabor filters as described here https://en.wikipedia.org/wiki/Gabor_filter. This should give us better results.

**Comment by dpattison3** [comment]
I attempted to do this over the summer. The computation is very intensive (runs very slow) and is far more complex than any current method. I don't see this as being something we should pursue as the current method is reasonably effective.
