### ISSUE TITLE
Ensure GPS noise doesn't effect where mapper believes the goal is

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#81]
Our GPS signal, and any sensor signal in general has noise in it. One way this manifests with our GPS is that while the robot is physically still, the robot believes it is bouncing around (approximately Gaussian about its actual position, depending on what satellites it sees).

Someone needs to see how the robot bouncing around effects the position of the goal. Even though it's impossible to know exactly where the robot is, we need to make sure that errors in our position estimation do not effect our estimation of where the goal is.

For more information, ask @barulicm (Matt)

**Comment by dpattison3** [comment]
This issue will be addressed in issue #68. Closing due to repeat
