### ISSUE TITLE
Retrain the neural network for parking lot navigation.

### ISSUE THREAD

**Issue by matthewhannay567** [RoboJackets/igvc-software#828]
Because this year's IGVC competition will be on a parking lot, we need to train a neural network to work with a parking lot.

**Comment by yyajima21** [comment]
@matthewhannay567, here are [some dataset](https://cloud.robojackets.org/apps/files/?dir=/RoboNav/Software/rosbags/2018-2019/parking-lot-2019&fileid=120997) collected from the parking lot. You may need to search some existing annotated dataset [here](https://cloud.robojackets.org/apps/files/?dir=/RoboNav/Software/dataset&). If you like to label some data, I used the following [website](https://github.com/wkentaro/labelme) to label images

**Comment by VAM7686** [comment]
The trained binary segmentation parking lot model can be found on the Robojackets cloud under `RoboNav/software/model/IGVCModel_10_parkinglot.pt`
