### ISSUE TITLE
cant find 

### ISSUE THREAD

**Issue by anas2908** [RoboJackets/igvc-software#837]
fatal: unable to open /home/anas/catkin_ws/igvc-software/.git/objects/pack/tmp_pack_WMKxMm: No such file or directory
fatal: index-pack failed

**Comment by VAM7686** [comment]
Hi, your workspace setup is not correct. The file structure should look something along the lines of this:
```
|-- catkin_ws
|   |-- src
|   |   |-- igvc_software
```
You can follow this [guide](http://wiki.ros.org/catkin/Tutorials/create_a_workspace) for creating a catkin workspace.
