### ISSUE TITLE
battery topic seems to always publish 0?

### ISSUE THREAD

**Issue by thaeds** [RoboJackets/igvc-software#88]
Look into how the battery topic works, what sensors it relies on, and ensure that it is accurately reporting the current battery level. (it seems to always publish 0)

**Comment by barulicm** [comment]
The battery topic is published by the light_controller node. The "sensor" is just a voltage divider fed into one of the Arduino's analogue pins. As for it always publishing 0, that may be related to some of the problems we were having with the light shield last weekend.

**Comment by rmkeezer** [comment]
This problem is unlikely to be remain relevant with the amount of changes in the past year and no testing can be done until the new robot is finished.
